name: Automated Testing

on: [ pull_request ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.6.0]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}


      - name: Testing Client
        run: |- 
          cd client && npm ci
          cd client && npm run test:prod

      - name: Testing Server
        run: |- 
          cd server && npm ci
          cd server && npm run test